---
title: "Lab10"
author: "Sophia Leiker"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(usethis)
library(janitor)

#New packages
library(beepr)
library(praise)
library(cowsay)
library(paletteer)
library(sf)
```

## beepr beeps
Use the function 'beep()' in the beepr package to make an audio alert when your code is done running

```{r, eval=FALSE}
#eval=false so it doesn't run every time you knit the document
#Creating a sequence(1:99) which would count upward, putting the rev in front of it makes it go backwards

for (i in rev(seq(1:999))) {
  
  print(paste(i, "bottles of beer on the wall")) 
}

#beep(4) #add this so at the end so a sound will be made after this part of the code has been run
```

## Praise and cowsay

Packages built with a single purpose: to be kind and fun.

```{r}
#praise("${Exclamation}, ${EXCLAIMATION}...${exclamation}!!!")

praise("Holy ${creating}, Batman - this code is ${ADJECTIVE}!")
```

Use cowsay::say() to make a character say something to you

usethis::use_git()
usethis::use_github()

## paletteer to access thousands of color palettes

```{r}
storms %>% 
  group_by(name) %>% 
  summarize(min_pressure = min(pressure, na.rm = TRUE)) %>%
  slice_min(n = 10, min_pressure) %>% #this is picking the 10 storms with lowest min pressure
  ggplot(aes(x = min_pressure, y = name)) +
  geom_col(aes(fill = name)) +
  scale_fill_paletteer_d("ggthemes::Green_Orange_Teal")
```

## One spatial data example

```{r}
vegetation <- read_sf("doc.kml") %>% 
  select(Name) %>% 
  clean_names()

#create a map using ggplot

#Update theme to theme minimal
#Fill color change nased on the vegetation
# color of line to NA (color = NA)

ggplot(data = vegetation) +
  geom_sf(aes(fill = name), color = NA) +
  theme_minimal() +
  scale_fill_paletteer_d("ggthemes::manyeys") +
  labs(title = "Jornada Basin LTER Vegetation",
       caption = "Source: Jornada LTER")
  

```

```{r}
ggsave(filename = "my_awesome_map.jpg", width = 8, height = 5)
```


